author:
  name: Björn Göttlicher
  email: bjoern@goettlicher-photo.com
  url: www.goettlicher-photo.com
title: Satire zwischen Fotokunst und Wortwitz
opengraph:
  type: 'https://www.facebook.com/lb.satiremagazin/'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8906721530947834
  brandStrength: 0.37667978066019714
  lightness: 0.6101436675526202
  brandColors:
    - '#E7E8D1'
    - '#D3CEAA'
    - '#FBF7E4'
    - '#424242'
    - '#8E001C'
  rhythmicContrast: 0.9619559922721237
typography_spectrum: 0.8369176
layout_spectrum: 0.702509
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/362db2df-7a4f-4c19-8734-5adc6e5a1c99.png
name: Der Laufbursche
